brew 'autoenv'
brew 'bash-completion'
brew 'docker'
brew 'fzf'
brew 'git'
brew 'node'
brew 'openssl'
brew 'openssl@1.1'
brew 'pgcli'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'python'
brew 'zsh'

cask 'docker'
cask 'flux'
cask 'google-chrome'
cask 'iterm2'
cask 'postman'
cask 'skype'
cask 'slack'
cask 'spotify'
cask 'steam'
cask 'telegram-desktop'
cask 'transmission'
cask 'visual-studio-code'
cask 'vlc'
cask 'whatsapp'

# quick-look plugins
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'quicklook-json'
